exclude:
  - './coverage/*'
  - './app/assets/stylesheets/base/normalize.scss'
  - './vendor/*'

linters:

  QualifyingElement:
    enabled: false

  SelectorFormat: # BEM validation
    convention: '^+[a-z]([-]?[a-z0-9]+)*(__[a-z0-9]([-]?[a-z0-9]+)*)?((_[a-z0-9]([-]?[a-z0-9]+)*){2})*'

  VendorPrefix:
    enabled: false
