language: ruby
rvm:
  - 2.2.2
before_script:
  - psql -c 'create database enlighten_test' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
deploy:
  provider: heroku
  on: master
  app: enlighten-prototype
  api_key:
    secure: G47qIFDLxmODxWezAXWYn+pyWF/tpbXrEW2AuxU8Z4FdhZYYy18wWqRW3H6/zh+i1IIb3p64iBT06E0LYTf3Ldwvrx+FB3bLZbO82uxSSabccYgh/XBTSSTw09nGcU6l1p1qtCkfWJpcrSPcvai9QEkvYOnBqFgJoIayjDbQtUIT3j7YCurUCxlqNMFb5r9IQLX/t1N9p2XkGIm06fUhG30Ngva6nFNah2jWklYz8NSbQRblDXzGO2oWS1Dlowu13EUANU5dwoC2sbhgVSk5NxMG193g5aiixeRVwyr+X0LiRgibO9G+9u9uI1QbsxS4U5j6in03RJU5mM/lAdJsmFv/j8m3DkWLImFDRIuZYBIbSBR3fwnAHeUfb5vma47xj8F4cJaO7KADm2lfua0APuM9XJQ8PfYPcriWjWQ7R2fwROTTeyLOnvoOV2utQ9W2vb2ooP0BGyUp0+SGvf0PHqYDZ5qKl+T5fxzbHG2kp6Vi5zoI6tuJGyIfC59VP8hS2xuOsCFH99jacxmgjtWV0NBH8sudyTkBDYyaoyflVAQO7+eyUclXI7cLY0PSUdvtkMd0NFmdHEYVUprFnUxiB2hGPSKzk7UOn+UA23VcE6emKffxavp2v/ydWrWBaJ6Tv+tFUZ0pyCDthjoeOSDn9rmzFbjAsxzr3l9es1TYh7U=
  run:
    - "rake db:migrate"
    - "restart"
