default: &default

  - provider: behance
    url: 'https://www.behance.net/#identifier'

  - provider: codepen
    url: 'http://codepen.io/#identifier'

  - provider: deviantart
    url: 'http://#identifier.deviantart.com/'

  - provider: dribbble
    url: 'https://dribbble.com/#identifier'

  - provider: facebook
    url: 'https://www.facebook.com/#identifier'

  - provider: flickr
    url: 'https://www.flickr.com/photos/#identifier'

  - provider: github
    url: 'https://github.com/#identifier'

  - provider: googleplus
    url: '#identifier'

  - provider: instagram
    url: 'https://instagram.com/#identifier'

  - provider: linkedin
    url: '#identifier'

  - provider: pinterest
    url: 'https://www.pinterest.com//#identifier'

  - provider: skype

  - provider: slideshare
    url: 'http://www.slideshare.net/#identifier'

  - provider: stackoverflow
    url: 'http://stackoverflow.com/users/#identifier'

  - provider: tumblr
    url: 'http://#identifier.tumblr.com/'

  - provider: twitter
    url: 'https://twitter.com/#identifier'

  - provider: youtube
    url: 'https://www.youtube.com/user/#identifier'

development: *default
test: *default
production: *default
